# This is the name of the workflow.
name: Java CI with Maven

# This tells GitHub WHEN to run the workflow.
# It will run on every 'push' to the 'main' branch,
# and on every 'pull_request' targeting the 'main' branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# This defines the actual job that will be run.
jobs:
  build:
    # The type of virtual machine to run the job on. 'ubuntu-latest' is a safe default.
    runs-on: ubuntu-latest

    # These are the individual steps of the job.
    steps:
      # Step 1: Checks out your repository's code so the workflow can use it.
      - uses: actions/checkout@v3

      # Step 2: Sets up the correct Java version. Modern Minecraft needs Java 17.
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Runs the Maven build command.
      # This is the same command you use to build the .jar file locally.
      - name: Build with Maven
        run: mvn -B package --file pom.xml